### ISSUE TITLE
Script does not get executed

### ISSUE THREAD

**Issue by kdobrev** [ansasi/VSCode-powershell-installation#1]
The addition of 
`# Call the function
Install-VSCode-Windows` does not exist in the script and when I add it manually  i get error: `Install-VSCode-Windows : The term 'Install-VSCode-Windows' is not recognized as the name of a cmdlet, function, script file, or operable program.`

**Comment by ansasi** [comment]
There is an error in the README. The function should be Install-VSC-Windows. I will correct it in the next pull request.

**Comment by ansasi** [comment]
Changes have are now in the main branch
