### ISSUE TITLE
Target path for shorcut not pointing to my install folder

### ISSUE THREAD

**Issue by kdobrev** [ansasi/VSCode-powershell-installation#2]
The shortcut path in the script  is `TargetPath 'C:\Program Files\Microsoft VS Code\Code.exe`, but my instalation goes to %localappdata%

**Comment by ansasi** [comment]
You're right. In case of local installation the target path for the shortcut should change to the user path, not use the global path.
That needs to be included in a separated PR.

**Comment by ansasi** [comment]
Changes have are now in the main branch
